# Test playbook to test all oracle modules
---
- hosts: localhost
  user: system
  #become: yes
  # become_user: oracle
  gather_facts: false


  vars:
      oracle_home: /opt/oracle/instantclient_18_3
      hostname: 172.17.208.10
      service_name: seora
      set_init_mode: sysdba
      set_init_user: sys
      user: system
      password: oracle
      oracle_env:
             ORACLE_HOME: "{{ oracle_home }}"
             LD_LIBRARY_PATH: "{{ oracle_home }}/lib"

      set_init: False
      restart_db: False
      init_parameters:
               - { name: db_recovery_file_dest_size, value: 4G, state: present, scope: both }
               - { name: db_recovery_file_dest, value: '+FRA', state: present, scope: both }
               - { name: pga_aggregate_target, value: 300M, state: present, scope: both }
               - { name: _parallel_statement_queuing, value: true, state: present, scope: both }
               - { name: sga_target, value: 900M, state: present, scope: spfile }
               - { name: sga_max_size, value: 900M, state: present, scope: spfile }
               - { name: open_cursors, value: 400, state: present, scope: both }
               - { name: processes, value: 700, state: present, scope: spfile }
               - { name: log_archive_dest_2, value: 'service=hippie2, LGWR ASYNC NOAFFIRM db_unique_name=hippie2 valid_for=(online_logfile,primary_role)', state: present, scope: both }


      tablespaces:
               - { name: newtbs, datafile: '+DATA', size: 5M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
               - { name: newundo, datafile: '+DATA', size: 5M, bigfile: false, autoextend: true, next: 5M, maxsize: 500M, content: undo, state: present }
               - { name: newtemp, datafile: '+DATA', size: 5M, bigfile: false, autoextend: on, next: 5M, maxsize: 500M, content: temp, state: present }

      dba_user:
           - schema: mercurio
             #schema_password_hash: B7C930D09B3AF263 # passwd = dbauser
             #schema_password_hash: mercurio
             schema_password: mercurio
             state: present
             default_tablespace: users
             grants:
                  - "dba"
                  
      passw_user:
           - schema: mercurio
             schema_password: 123456
             state: present
             default_tablespace: newtbs
             grants:
                  - "approle1"

      roles:
           - name: approle1
             role_grants:
                    - 'create session'
                    - 'select any table'
             state: present



  tasks:
  - name: Create DBA user
    oracle_user: hostname={{ hostname }} service_name={{ service_name }} mode=normal user={{ user }} password={{ password }} schema={{ item.0.schema }} schema_password={{ item.0.schema_password }} state={{ item.0.state }} default_tablespace={{ item.0.default_tablespace }} grants={{ item.1 }}
    #oracle_user: hostname={{ hostname }} service_name={{ service_name }} mode=normal user={{ user }} password={{ password }} schema={{ item.0.schema }} state={{ item.0.state }} default_tablespace={{ item.0.default_tablespace }} grants={{ item.1 }}
    environment: oracle_env
    with_subelements:
            - "{{ dba_user }}"
            - grants




